### ISSUE TITLE
No connections with 230400 Baud

### ISSUE THREAD

**Issue by cbmbas** [FozzTexx/tcpser#13]
There is a Typo in modem_core.c
mdm_responses[MDM_RESP_CONNECT_234000] = "CONNECT 230400";
should be:
mdm_responses[MDM_RESP_CONNECT_230400] = "CONNECT 230400";
and a missing case in serial.c for 230400 baud.

**Comment by FozzTexx** [comment]
Fixed in commit 9413ac

**Comment by cbmbas** [comment]
The case for 230400 in serial.c is still missing.

 



	
		
		
		
			switch (speed) {
		
		
			 
			case 115200:
		
		
			 
			bps_rate = B115200;
		
		
			 
			break;
		
		
			 
			case 57600:
		
		
			 
		
	



 

Gesendet: Montag, 01. Juli 2019 um 18:28 Uhr
Von: "FozzTexx" <notifications@github.com>
An: FozzTexx/tcpser <tcpser@noreply.github.com>
Cc: cbmbas <larrycool@web.de>, Author <author@noreply.github.com>
Betreff: Re: [FozzTexx/tcpser] No connections with 230400 Baud (#13)


Fixed in commit 9413ac
